# Generated by Django 4.1.7 on 2023-05-09 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_contacto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='telefono',
            field=models.TextField(default='Sin información', max_length=50),
        ),
    ]
