# Generated by Django 4.1.7 on 2023-08-12 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_contacto', '0005_alter_contacto_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='tipo_consulta',
            field=models.IntegerField(choices=[[0, 'Consulta'], [1, 'Sugerencia'], [2, 'Felicitaciones']]),
        ),
    ]
