# Generated by Django 4.1 on 2024-12-14 16:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Region', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.TextField(max_length=10, unique=True)),
                ('direccion', models.TextField()),
                ('telefono', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comuna', models.TextField()),
                ('codigo_region', models.ForeignKey(blank=True, db_column='codigo_region', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='a_inicio.region')),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=500)),
                ('m2_construido', models.FloatField(default=0)),
                ('m2_terreno', models.FloatField(default=0)),
                ('numero_banos', models.IntegerField(default=0)),
                ('numero_hab', models.IntegerField(default=0)),
                ('direccion', models.CharField(max_length=200)),
                ('estado', models.CharField(default='activo', max_length=50)),
                ('numero_est', models.IntegerField(default=0)),
                ('precio', models.CharField(max_length=200)),
                ('image_portada1', models.ImageField(default='bootcamp-desarrollo-aplicaciones-full-stack-python-trainee.png', upload_to='a_inicio/images')),
                ('image1', models.ImageField(blank=True, upload_to='a_inicio/images')),
                ('image2', models.ImageField(blank=True, upload_to='a_inicio/images')),
                ('image3', models.ImageField(blank=True, upload_to='a_inicio/images')),
                ('image4', models.ImageField(blank=True, upload_to='a_inicio/images')),
                ('image5', models.ImageField(blank=True, upload_to='a_inicio/images')),
                ('image6', models.ImageField(blank=True, upload_to='a_inicio/images')),
                ('image7', models.ImageField(blank=True, upload_to='a_inicio/images')),
                ('image8', models.ImageField(blank=True, upload_to='a_inicio/images')),
                ('image9', models.ImageField(blank=True, upload_to='a_inicio/images')),
                ('image10', models.ImageField(blank=True, upload_to='a_inicio/images')),
                ('date', models.DateTimeField(default=datetime.date.today)),
                ('mostrar', models.BooleanField(default=False)),
                ('preferencial', models.BooleanField(default=False)),
                ('id_comuna', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='a_inicio.comuna')),
                ('id_region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='a_inicio.region')),
                ('id_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
