# Generated by Django 4.1 on 2024-12-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_inicio', '0002_userstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstatus',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
