# Generated by Django 4.1 on 2024-12-14 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('a_inicio', '0003_alter_userstatus_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstatus',
            name='user',
        ),
        migrations.AddField(
            model_name='userstatus',
            name='cliente',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status', to='a_inicio.clientes'),
        ),
    ]
