# Generated by Django 4.1.7 on 2024-12-14 21:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_inicio', '0005_delete_userstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='date',
        ),
        migrations.AddField(
            model_name='clientes',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='clientes',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='estado',
            field=models.CharField(blank=True, default='activo', max_length=50, null=True),
        ),
    ]
