# Generated by Django 4.1 on 2025-01-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_inicio', '0006_remove_clientes_date_clientes_date_posted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='image_estado',
            field=models.ImageField(blank=True, null=True, upload_to='a_inicio/images'),
        ),
    ]
