# Generated by Django 4.1 on 2025-01-15 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_inicio', '0007_clientes_image_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='a_inicio/videos'),
        ),
    ]
