# Generated by Django 4.1 on 2025-01-15 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_inicio', '0008_clientes_video_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='preferencial',
        ),
    ]
