# Generated by Django 4.1 on 2025-01-16 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('a_inicio', '0009_remove_clientes_preferencial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_nation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_nation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_usuario', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='clientes',
            old_name='numero_banos',
            new_name='edad',
        ),
        migrations.RenameField(
            model_name='clientes',
            old_name='m2_construido',
            new_name='estatura',
        ),
        migrations.RenameField(
            model_name='clientes',
            old_name='numero_est',
            new_name='tarifa',
        ),
        migrations.RenameField(
            model_name='clientes',
            old_name='direccion',
            new_name='ubicacion',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='direccion',
            new_name='nickname',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='m2_terreno',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='numero_hab',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='precio',
        ),
        migrations.AddField(
            model_name='clientes',
            name='medida_alta',
            field=models.FloatField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='clientes',
            name='medida_baja',
            field=models.FloatField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='clientes',
            name='medida_media',
            field=models.FloatField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='clientes',
            name='nickname',
            field=models.CharField(default='No name', max_length=50),
        ),
        migrations.AddField(
            model_name='clientes',
            name='id_tipo_nation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='a_inicio.tipo_nation'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='id_tipo_usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='a_inicio.tipo_usuario'),
        ),
    ]
