# Generated by Django 4.1 on 2025-01-16 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_inicio', '0010_tipo_nation_tipo_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='nickname',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='telefono',
        ),
        migrations.AddField(
            model_name='clientes',
            name='telefono',
            field=models.CharField(default=0, max_length=12),
        ),
    ]
