# Generated by Django 4.1 on 2025-01-16 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_inicio', '0011_remove_profile_nickname_remove_profile_telefono_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='estado',
            field=models.CharField(blank=True, default='Disponible', max_length=50, null=True),
        ),
    ]
