# Generated by Django 4.1 on 2025-01-16 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_inicio', '0012_alter_clientes_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='estado',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
