# Generated by Django 4.1 on 2025-01-16 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_inicio', '0014_alter_clientes_medida_alta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='edad',
            field=models.IntegerField(default=0, max_length=2),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='estatura',
            field=models.FloatField(default=0, max_length=3),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='medida_alta',
            field=models.IntegerField(default=0, max_length=3),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='medida_baja',
            field=models.IntegerField(default=0, max_length=3),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='medida_media',
            field=models.IntegerField(default=0, max_length=3),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='nickname',
            field=models.CharField(default='No name', max_length=15),
        ),
    ]
