# Generated by Django 4.1 on 2025-01-16 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_inicio', '0015_alter_clientes_edad_alter_clientes_estatura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='estatura',
            field=models.IntegerField(default=0, max_length=3),
        ),
    ]
