# Generated by Django 4.1 on 2025-01-16 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_inicio', '0017_alter_clientes_estatura_alter_clientes_medida_alta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='edad',
            field=models.IntegerField(default=0),
        ),
    ]
