# Generated by Django 4.1 on 2025-01-16 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_inicio', '0018_alter_clientes_edad'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='dias_lab',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='clientes',
            name='horario',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='clientes',
            name='metro',
            field=models.CharField(default='', max_length=200),
        ),
    ]
