# Generated by Django 4.1 on 2025-01-16 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_inicio', '0019_clientes_dias_lab_clientes_horario_clientes_metro'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='servicios',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='clientes',
            name='servicios_add',
            field=models.CharField(default='', max_length=200),
        ),
    ]
