# Generated by Django 4.1 on 2025-01-16 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_inicio', '0020_clientes_servicios_clientes_servicios_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='servicios_add',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
