# Generated by Django 4.1 on 2025-01-19 16:23

import a_inicio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_inicio', '0021_alter_clientes_servicios_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='nickname',
            field=models.CharField(default='No name', max_length=30),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='a_inicio/videos', validators=[a_inicio.models.validar_duracion_video]),
        ),
    ]
