# Generated by Django 4.1 on 2025-01-19 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_inicio', '0022_alter_clientes_nickname_alter_clientes_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='descripcion',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
