# Generated by Django 4.1 on 2025-01-20 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_inicio', '0023_alter_clientes_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='estatura',
            field=models.CharField(max_length=3),
        ),
    ]
