# Generated by Django 4.1 on 2025-01-20 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_inicio', '0024_alter_clientes_estatura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='estatura',
            field=models.CharField(max_length=4),
        ),
    ]
