# Generated by Django 4.1 on 2025-01-20 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_inicio', '0025_alter_clientes_estatura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='telefono',
            field=models.CharField(default=0, max_length=9),
        ),
    ]
