# Generated by Django 4.1 on 2025-01-23 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_inicio', '0026_alter_clientes_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comuna',
            name='comuna',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='region',
            name='Region',
            field=models.CharField(max_length=100),
        ),
    ]
