# Generated by Django 4.1 on 2025-01-25 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('a_inicio', '0027_alter_comuna_comuna_alter_region_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dias_lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_lab', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='dias_lab',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='horario',
        ),
        migrations.AddField(
            model_name='clientes',
            name='id_dias_lab',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='a_inicio.dias_lab'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='id_horario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='a_inicio.horario'),
        ),
    ]
