# Generated by Django 4.1 on 2025-01-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_inicio', '0028_dias_lab_horario_remove_clientes_dias_lab_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='rut',
            field=models.TextField(max_length=20, unique=True),
        ),
    ]
