# Generated by Django 4.1 on 2025-01-27 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_inicio', '0029_alter_profile_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='image1',
            field=models.ImageField(upload_to='a_inicio/images'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='image2',
            field=models.ImageField(upload_to='a_inicio/images'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='image3',
            field=models.ImageField(upload_to='a_inicio/images'),
        ),
    ]
