# Generated by Django 4.1 on 2025-01-29 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('a_inicio', '0031_alter_clientes_metro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='servicios',
        ),
        migrations.AddField(
            model_name='clientes',
            name='id_servicio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='a_inicio.servicio'),
        ),
    ]
